- hosts: cisco
  vars:
    suffix: shver
  gather_facts: no
  sudo: yes

  tasks:
   - name: execute command
     local_action:
       module: ios_command
       authorize: yes
       auth_pass: "{{ en }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       host: "{{ inventory_hostname }}"
       commands:
         - show clock
         - show version
     register: result

   - include: tasks/result_allout.yml
