# tasks/result_allout.yml
# 
# inventory vars: 
#   dir_tmp, dir_log
#
# required vars:
#   result, suffix

- name: log write out
  local_action: template src=./tasks/template.j2 dest={{ dir_tmp }}/{{ inventory_hostname }}-{{ suffix }}.log

- name: mkdir all
  file: path={{ dir_log }}/all state=directory
  delegate_to: localhost

- name: parse config
  local_action: shell HOSTLOG=`awk '/hostname/ {print $2}' {{ dir_tmp }}/{{ inventory_hostname }}-{{ suffix }}.log
                | sed -e 's/\"/:/'`
                ; cat {{ dir_tmp }}/{{ inventory_hostname }}-{{ suffix }}.log 
                | sed -e 's/        \"//g' -e 's/",//g' -e "1,2d"
                | sed -e 's/^    ], //' -e 's/^    \[//' -e 's/"$//' -e 's/\\"/\"/g'
                | head -n -2
                | sed -e "s/^/$HOSTLOG /"
                >> {{ dir_log }}/all/{{ suffix }}.log

- name: backup file by date
  local_action: shell cp {{ dir_log }}/all/{{ suffix }}.log
                         {{ dir_log }}/all/{{ suffix }}-`date +'%Y%m%d'`.log 


- name: remove logfile
  local_action: file path={{ dir_tmp }}/{{ inventory_hostname }}-{{ suffix }}.log state=absent
